[package]
name = "zuc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-multipart = "0.6.1"
actix-web = { version = "4", features = ["openssl"] }
des = "0.8.1"
futures = "0.3.30"
openssl = { version = "0.10" }
rc4 = "=0.1.0"